version: '3.2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak-authenticator:
    container_name: keyvi
    build: .
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JDBC_PARAMS: "useSSL=true"
      KEYCLOAK_HOSTNAME: yivisso.com
    ports:
      - '8443:8443'
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data_volume:
    driver: local
